name: nagad_payment_gateway
description: "A Flutter package for Nagad Online Payment API (Sandbox) Integration"
version: 0.3.1
homepage: https://github.com/muhibbin-munna/nagad_flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  encrypt: ^5.0.3
  webview_flutter: ^4.10.0
  intl: ^0.20.2
  hex: ^0.2.0
  connectivity_plus: ^6.1.3  # for getting the ip address

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0