name: nagad_payment_gateway
description: "A Flutter package for Nagad Online Payment API (Sandbox) Integration"
version: 0.2.0
homepage: https://github.com/muhibbin-munna/nagad_flutter

environment:
  sdk: '>=3.6.1 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  http: any
  encrypt: any
  webview_flutter: any
  intl: any
  hex: any
  connectivity_plus: any  # for getting the ip address

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any